version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/laravel5-sample/build
hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: ec2-user
