version: 0.2

phases:
  install:
    commands:
      - echo "install start"
      - apt-get -yq update && apt-get -yq install zip
  pre_build:
    commands:
      - echo "pre_build start"
      - composer install
      - composer dump-autoload
      - cp .env.example .env
      - php artisan key:generate
  build:
    commands:
      - echo "build start"
      - vendor/bin/phpunit
  post_build:
    commands:
      - echo "post_build start"
      - cd ../
      - zip -rq laravel5-sample.zip laravel5-sample
artifacts:
  files:
    - ../laravel5-sample.zip
  # discard-paths: yes
  # base-directory: location
