version: 0.2

phases:
  #install:
    #commands:
      # - command
      # - command
  pre_build:
    commands:
      - echo "pre_build start"
      - composer install
      - composer dump-autoload
      - cp .env.example .env
      - php artisan key:generate
  build:
    commands:
      - echo "build start"
      - vendor/bin/phpunit
  #post_build:
    #commands:
      #- command
      #- command
artifacts:
  files:
    - '**/*'
  discard-paths: false
